name: Snyk Scan

on:
  pull_request:
    branches:
      - master  # Cambia 'master' por 'main' si usas 'main' como tu rama principal

jobs:
  snyk:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10.7'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements_cpu.txt
        pip install -r requirements_gpu.txt

    - name: Install Snyk CLI
      run: npm install -g snyk

    - name: Run Snyk Code to check for vulnerabilities
      run: snyk code test --sarif > snyk-code.sarif || exit 1
