name: Snyk Security Scan

on:
  pull_request:
    branches:
      - master

jobs:
  snyk:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Snyk CLI
        run: npm install -g snyk

      - name: Run Snyk to check for vulnerabilities
        run: snyk test --all-sub-projects

      - name: Snyk Monitor
        run: snyk monitor

      - name: Check Snyk test result
        id: snyk-test
        run: |
          snyk test --all-sub-projects --json > snyk-results.json
          if grep -q '"severity": "high"\|"severity": "critical"' snyk-results.json; then
            echo "Critical vulnerabilities found! Failing the build."
            exit 1
          fi
